# This file was generated by GoReleaser. DO NOT EDIT.
cask "ip2cr" do
  name "ip2cr"
  desc "IP-2-CloudResource: correlate an IP address with its associated cloud resource"
  homepage "https://github.com/magneticstain/ip-2-cloudresource"
  version "3.1.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ip2cr"

  on_macos do
    on_intel do
      url "https://github.com/magneticstain/ip-2-cloudresource/releases/download/v#{version}/ip-2-cloudresource_#{version}_darwin_amd64.tar.gz"
      sha256 "7bd3803f0b1e21bc70796c750baaba547cd5159fcdded00a667949cb30623c1b"
    end
    on_arm do
      url "https://github.com/magneticstain/ip-2-cloudresource/releases/download/v#{version}/ip-2-cloudresource_#{version}_darwin_arm64.tar.gz"
      sha256 "1fbf1fc41f6f9bb356b0a57bd4e7332dc67dc0c7c9c8008634de8cc476e9ccaf"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/magneticstain/ip-2-cloudresource/releases/download/v#{version}/ip-2-cloudresource_#{version}_linux_amd64.tar.gz"
      sha256 "e6d272052ebb1cdc790f9df42f26fdfc28f88bb16f75267cc2797a3a813a9cdb"
    end
    on_arm do
      url "https://github.com/magneticstain/ip-2-cloudresource/releases/download/v#{version}/ip-2-cloudresource_#{version}_linux_arm64.tar.gz"
      sha256 "cb3593bffcf8e28a3f0eeb022436c262169318f5db6260a39685b6df95a82239"
    end
  end

  # No zap stanza required
end
