# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ip2cr < Formula
  desc "IP-2-CloudResource: correlate an IP address with its associated cloud resource"
  homepage "https://github.com/magneticstain/ip-2-cloudresource"
  version "1.3.0"
  license "MIT"

  on_macos do
    url "https://github.com/magneticstain/ip-2-cloudresource/releases/download/v1.3.0/ip-2-cloudresource_Darwin_x86_64_v1.3.0.tar.gz"
    sha256 "f7aa1d286e2a7d0e0754da67f973ab4b1aaad3cc19806addabe4eb593e5cb736"

    def install
      bin.install "ip2cr"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Ip2cr
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/magneticstain/ip-2-cloudresource/releases/download/v1.3.0/ip-2-cloudresource_Linux_x86_64_v1.3.0.tar.gz"
      sha256 "8ec2e2be84795846f70ae0a771f12e8f931fc3089d81a06b7102e9deed45a067"

      def install
        bin.install "ip2cr"
      end
    end
  end

  test do
    system "#{bin}/ip2cr --help"
  end
end
