# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ip2cr < Formula
  desc "IP-2-CloudResource: correlate an IP address with its associated cloud resource"
  homepage "https://github.com/magneticstain/ip-2-cloudresource"
  version "1.4.0"
  license "MIT"

  on_macos do
    url "https://github.com/magneticstain/ip-2-cloudresource/releases/download/v1.4.0/ip-2-cloudresource_Darwin_x86_64_v1.4.0.tar.gz"
    sha256 "946ede745ef3c88bf8f32866dcd6fca940b716530839b2f2ad9922e9a6cf2e3d"

    def install
      bin.install "ip2cr"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Ip2cr
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/magneticstain/ip-2-cloudresource/releases/download/v1.4.0/ip-2-cloudresource_Linux_x86_64_v1.4.0.tar.gz"
      sha256 "6190e6915c47c1734aeaa3b34a6ac63a975e8f73f0340f8e96c0bd120d9337aa"

      def install
        bin.install "ip2cr"
      end
    end
  end

  test do
    system "#{bin}/ip2cr --help"
  end
end
